name: Build Android
run-name: Build Android
on:
  workflow_dispatch: {}
jobs:
  Build_Android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: app-android.apk
          path: build/app/outputs/flutter-apk/app-release.apk
